/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Connection (void)
{
  GtkWidget *Connection;
  GtkWidget *fixed1;
  GtkWidget *entrylogin;
  GtkWidget *entrypasswd;
  GtkWidget *labelconnex2;
  GtkWidget *labelconnx1;
  GtkWidget *Connection;
  GtkWidget *outputerreur;

  Connection = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Connection), _("Connection"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Connection), fixed1);

  entrylogin = gtk_entry_new ();
  gtk_widget_show (entrylogin);
  gtk_fixed_put (GTK_FIXED (fixed1), entrylogin, 168, 72);
  gtk_widget_set_size_request (entrylogin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrylogin), 8226);

  entrypasswd = gtk_entry_new ();
  gtk_widget_show (entrypasswd);
  gtk_fixed_put (GTK_FIXED (fixed1), entrypasswd, 168, 128);
  gtk_widget_set_size_request (entrypasswd, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrypasswd), 8226);

  labelconnex2 = gtk_label_new (_("Mot de Passe :"));
  gtk_widget_show (labelconnex2);
  gtk_fixed_put (GTK_FIXED (fixed1), labelconnex2, 16, 128);
  gtk_widget_set_size_request (labelconnex2, 144, 24);

  labelconnx1 = gtk_label_new (_("Login :"));
  gtk_widget_show (labelconnx1);
  gtk_fixed_put (GTK_FIXED (fixed1), labelconnx1, 80, 72);
  gtk_widget_set_size_request (labelconnx1, 64, 32);

  Connection = gtk_button_new_with_mnemonic (_("Connection"));
  gtk_widget_show (Connection);
  gtk_fixed_put (GTK_FIXED (fixed1), Connection, 96, 192);
  gtk_widget_set_size_request (Connection, 96, 56);

  outputerreur = gtk_label_new ("");
  gtk_widget_show (outputerreur);
  gtk_fixed_put (GTK_FIXED (fixed1), outputerreur, 208, 192);
  gtk_widget_set_size_request (outputerreur, 200, 80);

  g_signal_connect ((gpointer) Connection, "clicked",
                    G_CALLBACK (on_Connection_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Connection, Connection, "Connection");
  GLADE_HOOKUP_OBJECT (Connection, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Connection, entrylogin, "entrylogin");
  GLADE_HOOKUP_OBJECT (Connection, entrypasswd, "entrypasswd");
  GLADE_HOOKUP_OBJECT (Connection, labelconnex2, "labelconnex2");
  GLADE_HOOKUP_OBJECT (Connection, labelconnx1, "labelconnx1");
  GLADE_HOOKUP_OBJECT (Connection, Connection, "Connection");
  GLADE_HOOKUP_OBJECT (Connection, outputerreur, "outputerreur");

  return Connection;
}

GtkWidget*
create_EspaceAdmin (void)
{
  GtkWidget *EspaceAdmin;
  GtkWidget *fixed2;
  GtkWidget *Gcache;
  GtkWidget *Gpageacceuil;
  GtkWidget *reclamation;
  GtkWidget *statistique;
  GtkWidget *planhoraire;
  GtkWidget *deconnection;
  GtkWidget *Gcompte;

  EspaceAdmin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (EspaceAdmin), _("Espace Admin"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (EspaceAdmin), fixed2);

  Gcache = gtk_button_new_with_mnemonic (_("Gestion de finance"));
  gtk_widget_show (Gcache);
  gtk_fixed_put (GTK_FIXED (fixed2), Gcache, 216, 48);
  gtk_widget_set_size_request (Gcache, 152, 32);

  Gpageacceuil = gtk_button_new_with_mnemonic (_("Gestion page d'acceuil"));
  gtk_widget_show (Gpageacceuil);
  gtk_fixed_put (GTK_FIXED (fixed2), Gpageacceuil, 32, 128);
  gtk_widget_set_size_request (Gpageacceuil, 120, 40);

  reclamation = gtk_button_new_with_mnemonic (_("Reclamation"));
  gtk_widget_show (reclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), reclamation, 224, 120);
  gtk_widget_set_size_request (reclamation, 152, 48);

  statistique = gtk_button_new_with_mnemonic (_("Statistique"));
  gtk_widget_show (statistique);
  gtk_fixed_put (GTK_FIXED (fixed2), statistique, 40, 208);
  gtk_widget_set_size_request (statistique, 120, 48);

  planhoraire = gtk_button_new_with_mnemonic (_("Planning des horraires de travail"));
  gtk_widget_show (planhoraire);
  gtk_fixed_put (GTK_FIXED (fixed2), planhoraire, 224, 208);
  gtk_widget_set_size_request (planhoraire, 144, 48);

  deconnection = gtk_button_new_with_mnemonic (_("D\303\251connection"));
  gtk_widget_show (deconnection);
  gtk_fixed_put (GTK_FIXED (fixed2), deconnection, 256, 288);
  gtk_widget_set_size_request (deconnection, 128, 32);

  Gcompte = gtk_button_new_with_mnemonic (_("Gestion compte utilisateur"));
  gtk_widget_show (Gcompte);
  gtk_fixed_put (GTK_FIXED (fixed2), Gcompte, 32, 48);
  gtk_widget_set_size_request (Gcompte, 120, 40);

  g_signal_connect ((gpointer) Gcompte, "clicked",
                    G_CALLBACK (on_Gcompte_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (EspaceAdmin, EspaceAdmin, "EspaceAdmin");
  GLADE_HOOKUP_OBJECT (EspaceAdmin, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (EspaceAdmin, Gcache, "Gcache");
  GLADE_HOOKUP_OBJECT (EspaceAdmin, Gpageacceuil, "Gpageacceuil");
  GLADE_HOOKUP_OBJECT (EspaceAdmin, reclamation, "reclamation");
  GLADE_HOOKUP_OBJECT (EspaceAdmin, statistique, "statistique");
  GLADE_HOOKUP_OBJECT (EspaceAdmin, planhoraire, "planhoraire");
  GLADE_HOOKUP_OBJECT (EspaceAdmin, deconnection, "deconnection");
  GLADE_HOOKUP_OBJECT (EspaceAdmin, Gcompte, "Gcompte");

  return EspaceAdmin;
}

GtkWidget*
create_comptes (void)
{
  GtkWidget *comptes;
  GtkWidget *fixed3;
  GtkWidget *ouvrircompte;
  GtkWidget *retrnE1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label3;
  GtkWidget *comboboxentry1;

  comptes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (comptes), _("Gestion compte"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (comptes), fixed3);

  ouvrircompte = gtk_button_new_with_mnemonic (_("Ouvrir"));
  gtk_widget_show (ouvrircompte);
  gtk_fixed_put (GTK_FIXED (fixed3), ouvrircompte, 168, 168);
  gtk_widget_set_size_request (ouvrircompte, 74, 29);

  retrnE1 = gtk_button_new ();
  gtk_widget_show (retrnE1);
  gtk_fixed_put (GTK_FIXED (fixed3), retrnE1, 320, 256);
  gtk_widget_set_size_request (retrnE1, 88, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (retrnE1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 0);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxentry1, 112, 64);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Comptes Adh\303\251rents"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Comptes Coachs"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Comptes Kin\303\251sith\303\251rapeutes"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Comptes M\303\251decin Nutritionnistes"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Comptes Di\303\251t\303\251ticien"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Comptes Agents de N\303\251toyage"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (comptes, comptes, "comptes");
  GLADE_HOOKUP_OBJECT (comptes, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (comptes, ouvrircompte, "ouvrircompte");
  GLADE_HOOKUP_OBJECT (comptes, retrnE1, "retrnE1");
  GLADE_HOOKUP_OBJECT (comptes, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (comptes, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (comptes, image1, "image1");
  GLADE_HOOKUP_OBJECT (comptes, label3, "label3");
  GLADE_HOOKUP_OBJECT (comptes, comboboxentry1, "comboboxentry1");

  return comptes;
}

GtkWidget*
create_adherent (void)
{
  GtkWidget *adherent;
  GtkWidget *fixed5;
  GtkWidget *label4;
  GtkWidget *modifadh;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label6;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview2;
  GtkWidget *entryrechercheadh;
  GtkWidget *label20;
  GtkWidget *suppradh;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label7;
  GtkWidget *labelexistant;
  GtkWidget *retrnC1;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label8;
  GtkWidget *ajoutadh;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label5;

  adherent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (adherent), _("Adh\303\251rent"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (adherent), fixed5);

  label4 = gtk_label_new (_("Liste des Adh\303\251rents :"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed5), label4, 56, 48);
  gtk_widget_set_size_request (label4, 176, 24);

  modifadh = gtk_button_new ();
  gtk_widget_show (modifadh);
  gtk_fixed_put (GTK_FIXED (fixed5), modifadh, 176, 384);
  gtk_widget_set_size_request (modifadh, 232, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (modifadh), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox3), label6, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed5), scrolledwindow1, 88, 80);
  gtk_widget_set_size_request (scrolledwindow1, 584, 256);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview2);

  entryrechercheadh = gtk_entry_new ();
  gtk_widget_show (entryrechercheadh);
  gtk_fixed_put (GTK_FIXED (fixed5), entryrechercheadh, 248, 344);
  gtk_widget_set_size_request (entryrechercheadh, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryrechercheadh), 8226);

  label20 = gtk_label_new (_("Recherche  par N\302\260CIN:"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed5), label20, 80, 352);
  gtk_widget_set_size_request (label20, 160, 16);

  suppradh = gtk_button_new ();
  gtk_widget_show (suppradh);
  gtk_fixed_put (GTK_FIXED (fixed5), suppradh, 416, 384);
  gtk_widget_set_size_request (suppradh, 216, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (suppradh), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox4), label7, FALSE, FALSE, 0);

  labelexistant = gtk_label_new ("");
  gtk_widget_show (labelexistant);
  gtk_fixed_put (GTK_FIXED (fixed5), labelexistant, 456, 344);
  gtk_widget_set_size_request (labelexistant, 216, 32);

  retrnC1 = gtk_button_new ();
  gtk_widget_show (retrnC1);
  gtk_fixed_put (GTK_FIXED (fixed5), retrnC1, 664, 392);
  gtk_widget_set_size_request (retrnC1, 120, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (retrnC1), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox5), label8, FALSE, FALSE, 0);

  ajoutadh = gtk_button_new ();
  gtk_widget_show (ajoutadh);
  gtk_fixed_put (GTK_FIXED (fixed5), ajoutadh, 400, 24);
  gtk_widget_set_size_request (ajoutadh, 328, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (ajoutadh), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Ajouter un nouveau compte adh\303\251rent"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox2), label5, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) modifadh, "clicked",
                    G_CALLBACK (on_modifadh_clicked),
                    NULL);
  g_signal_connect ((gpointer) suppradh, "clicked",
                    G_CALLBACK (on_suppradh_clicked),
                    NULL);
  g_signal_connect ((gpointer) retrnC1, "clicked",
                    G_CALLBACK (on_retrnC1_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajoutadh, "clicked",
                    G_CALLBACK (on_ajoutadh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (adherent, adherent, "adherent");
  GLADE_HOOKUP_OBJECT (adherent, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (adherent, label4, "label4");
  GLADE_HOOKUP_OBJECT (adherent, modifadh, "modifadh");
  GLADE_HOOKUP_OBJECT (adherent, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (adherent, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (adherent, image3, "image3");
  GLADE_HOOKUP_OBJECT (adherent, label6, "label6");
  GLADE_HOOKUP_OBJECT (adherent, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (adherent, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (adherent, entryrechercheadh, "entryrechercheadh");
  GLADE_HOOKUP_OBJECT (adherent, label20, "label20");
  GLADE_HOOKUP_OBJECT (adherent, suppradh, "suppradh");
  GLADE_HOOKUP_OBJECT (adherent, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (adherent, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (adherent, image4, "image4");
  GLADE_HOOKUP_OBJECT (adherent, label7, "label7");
  GLADE_HOOKUP_OBJECT (adherent, labelexistant, "labelexistant");
  GLADE_HOOKUP_OBJECT (adherent, retrnC1, "retrnC1");
  GLADE_HOOKUP_OBJECT (adherent, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (adherent, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (adherent, image5, "image5");
  GLADE_HOOKUP_OBJECT (adherent, label8, "label8");
  GLADE_HOOKUP_OBJECT (adherent, ajoutadh, "ajoutadh");
  GLADE_HOOKUP_OBJECT (adherent, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (adherent, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (adherent, image2, "image2");
  GLADE_HOOKUP_OBJECT (adherent, label5, "label5");

  return adherent;
}

GtkWidget*
create_ajoutadh (void)
{
  GtkWidget *ajoutadh;
  GtkWidget *fixed6;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label13;
  GtkWidget *comboboxentryajoutadhmois;
  GtkWidget *comboboxentryajoutadhjour;
  GtkWidget *comboboxentryajoutadhannee;
  GtkWidget *entrynomadh;
  GtkWidget *entryprenomadh;
  GtkWidget *entryloginadh;
  GtkWidget *label17;
  GtkWidget *entrymdpssadh;
  GtkWidget *Enregistrer;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label19;
  GtkWidget *retrnA1;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label18;

  ajoutadh = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajoutadh), _("Ajout Adh\303\251rent"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (ajoutadh), fixed6);

  label9 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed6), label9, 48, 48);
  gtk_widget_set_size_request (label9, 96, 24);

  label10 = gtk_label_new (_("Prenom:"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed6), label10, 48, 96);
  gtk_widget_set_size_request (label10, 88, 24);

  label11 = gtk_label_new (_("Date de Naissance :"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed6), label11, 40, 152);
  gtk_widget_set_size_request (label11, 152, 24);

  label12 = gtk_label_new (_("Login :"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed6), label12, 432, 48);
  gtk_widget_set_size_request (label12, 96, 32);

  label14 = gtk_label_new (_("Mois:"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed6), label14, 264, 208);
  gtk_widget_set_size_request (label14, 49, 17);

  label15 = gtk_label_new (_("Ann\303\251e:"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed6), label15, 432, 208);
  gtk_widget_set_size_request (label15, 49, 17);

  label13 = gtk_label_new (_("Jour:"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed6), label13, 96, 200);
  gtk_widget_set_size_request (label13, 72, 24);

  comboboxentryajoutadhmois = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryajoutadhmois);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxentryajoutadhmois, 320, 208);
  gtk_widget_set_size_request (comboboxentryajoutadhmois, 109, 21);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhmois), _("Janvier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhmois), _("F\303\251vrier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhmois), _("Mars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhmois), _("Avril"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhmois), _("Mai"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhmois), _("Juin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhmois), _("Juillet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhmois), _("Ao\303\273t"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhmois), _("Septembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhmois), _("Octobre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhmois), _("Novembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhmois), _("D\303\251cembre"));

  comboboxentryajoutadhjour = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryajoutadhjour);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxentryajoutadhjour, 160, 208);
  gtk_widget_set_size_request (comboboxentryajoutadhjour, 109, 21);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhjour), _("31"));

  comboboxentryajoutadhannee = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryajoutadhannee);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxentryajoutadhannee, 488, 208);
  gtk_widget_set_size_request (comboboxentryajoutadhannee, 101, 21);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1980"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1981"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1982"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1983"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1984"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1985"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1986"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1987"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1988"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1989"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1990"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1991"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1992"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1993"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1994"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1995"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1996"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1997"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1998"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("1999"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("2000"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryajoutadhannee), _("2001"));

  entrynomadh = gtk_entry_new ();
  gtk_widget_show (entrynomadh);
  gtk_fixed_put (GTK_FIXED (fixed6), entrynomadh, 128, 48);
  gtk_widget_set_size_request (entrynomadh, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynomadh), 8226);

  entryprenomadh = gtk_entry_new ();
  gtk_widget_show (entryprenomadh);
  gtk_fixed_put (GTK_FIXED (fixed6), entryprenomadh, 128, 96);
  gtk_widget_set_size_request (entryprenomadh, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenomadh), 8226);

  entryloginadh = gtk_entry_new ();
  gtk_widget_show (entryloginadh);
  gtk_fixed_put (GTK_FIXED (fixed6), entryloginadh, 504, 48);
  gtk_widget_set_size_request (entryloginadh, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryloginadh), 8226);

  label17 = gtk_label_new (_("Mot de Passe:"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed6), label17, 392, 112);
  gtk_widget_set_size_request (label17, 120, 16);

  entrymdpssadh = gtk_entry_new ();
  gtk_widget_show (entrymdpssadh);
  gtk_fixed_put (GTK_FIXED (fixed6), entrymdpssadh, 504, 104);
  gtk_widget_set_size_request (entrymdpssadh, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymdpssadh), 8226);

  Enregistrer = gtk_button_new ();
  gtk_widget_show (Enregistrer);
  gtk_fixed_put (GTK_FIXED (fixed6), Enregistrer, 240, 320);
  gtk_widget_set_size_request (Enregistrer, 120, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (Enregistrer), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox7), label19, FALSE, FALSE, 0);

  retrnA1 = gtk_button_new ();
  gtk_widget_show (retrnA1);
  gtk_fixed_put (GTK_FIXED (fixed6), retrnA1, 408, 320);
  gtk_widget_set_size_request (retrnA1, 120, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (retrnA1), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox6), label18, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) Enregistrer, "clicked",
                    G_CALLBACK (on_Enregistrer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajoutadh, ajoutadh, "ajoutadh");
  GLADE_HOOKUP_OBJECT (ajoutadh, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (ajoutadh, label9, "label9");
  GLADE_HOOKUP_OBJECT (ajoutadh, label10, "label10");
  GLADE_HOOKUP_OBJECT (ajoutadh, label11, "label11");
  GLADE_HOOKUP_OBJECT (ajoutadh, label12, "label12");
  GLADE_HOOKUP_OBJECT (ajoutadh, label14, "label14");
  GLADE_HOOKUP_OBJECT (ajoutadh, label15, "label15");
  GLADE_HOOKUP_OBJECT (ajoutadh, label13, "label13");
  GLADE_HOOKUP_OBJECT (ajoutadh, comboboxentryajoutadhmois, "comboboxentryajoutadhmois");
  GLADE_HOOKUP_OBJECT (ajoutadh, comboboxentryajoutadhjour, "comboboxentryajoutadhjour");
  GLADE_HOOKUP_OBJECT (ajoutadh, comboboxentryajoutadhannee, "comboboxentryajoutadhannee");
  GLADE_HOOKUP_OBJECT (ajoutadh, entrynomadh, "entrynomadh");
  GLADE_HOOKUP_OBJECT (ajoutadh, entryprenomadh, "entryprenomadh");
  GLADE_HOOKUP_OBJECT (ajoutadh, entryloginadh, "entryloginadh");
  GLADE_HOOKUP_OBJECT (ajoutadh, label17, "label17");
  GLADE_HOOKUP_OBJECT (ajoutadh, entrymdpssadh, "entrymdpssadh");
  GLADE_HOOKUP_OBJECT (ajoutadh, Enregistrer, "Enregistrer");
  GLADE_HOOKUP_OBJECT (ajoutadh, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (ajoutadh, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (ajoutadh, image7, "image7");
  GLADE_HOOKUP_OBJECT (ajoutadh, label19, "label19");
  GLADE_HOOKUP_OBJECT (ajoutadh, retrnA1, "retrnA1");
  GLADE_HOOKUP_OBJECT (ajoutadh, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (ajoutadh, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (ajoutadh, image6, "image6");
  GLADE_HOOKUP_OBJECT (ajoutadh, label18, "label18");

  return ajoutadh;
}

GtkWidget*
create_modifadh (void)
{
  GtkWidget *modifadh;
  GtkWidget *fixed7;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label27;
  GtkWidget *label29;
  GtkWidget *label31;
  GtkWidget *label25;
  GtkWidget *label24;
  GtkWidget *label26;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *outputloginadh;
  GtkWidget *entry10;
  GtkWidget *outputmdpssadh;
  GtkWidget *entry11;
  GtkWidget *outputnomadh;
  GtkWidget *outputjouradh;
  GtkWidget *outputmoisadh;
  GtkWidget *outputanneeadh;
  GtkWidget *comboboxentry7;
  GtkWidget *comboboxentry6;
  GtkWidget *comboboxentry5;
  GtkWidget *validermodifadh;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label37;
  GtkWidget *retrnA2;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label38;
  GtkWidget *outputprenomadh;

  modifadh = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifadh), _("Modifier"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (modifadh), fixed7);

  label22 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed7), label22, 40, 56);
  gtk_widget_set_size_request (label22, 80, 32);

  label23 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed7), label23, 32, 128);
  gtk_widget_set_size_request (label23, 88, 24);

  label27 = gtk_label_new (_("Jour :"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed7), label27, 72, 240);
  gtk_widget_set_size_request (label27, 72, 24);

  label29 = gtk_label_new (_("Mois:"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed7), label29, 224, 240);
  gtk_widget_set_size_request (label29, 80, 24);

  label31 = gtk_label_new (_("Ann\303\251e:"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed7), label31, 392, 240);
  gtk_widget_set_size_request (label31, 96, 24);

  label25 = gtk_label_new (_("Login:"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed7), label25, 424, 56);
  gtk_widget_set_size_request (label25, 80, 24);

  label24 = gtk_label_new (_("Date de Naissance :"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed7), label24, 40, 200);
  gtk_widget_set_size_request (label24, 152, 24);

  label26 = gtk_label_new (_("Mot de Passe:"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed7), label26, 384, 120);
  gtk_widget_set_size_request (label26, 144, 24);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed7), entry8, 256, 56);
  gtk_widget_set_size_request (entry8, 152, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed7), entry9, 640, 56);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  outputloginadh = gtk_label_new ("");
  gtk_widget_show (outputloginadh);
  gtk_fixed_put (GTK_FIXED (fixed7), outputloginadh, 496, 56);
  gtk_widget_set_size_request (outputloginadh, 144, 24);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed7), entry10, 648, 120);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  outputmdpssadh = gtk_label_new ("");
  gtk_widget_show (outputmdpssadh);
  gtk_fixed_put (GTK_FIXED (fixed7), outputmdpssadh, 520, 120);
  gtk_widget_set_size_request (outputmdpssadh, 136, 24);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed7), entry11, 256, 128);
  gtk_widget_set_size_request (entry11, 136, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  outputnomadh = gtk_label_new ("");
  gtk_widget_show (outputnomadh);
  gtk_fixed_put (GTK_FIXED (fixed7), outputnomadh, 112, 64);
  gtk_widget_set_size_request (outputnomadh, 144, 24);

  outputjouradh = gtk_label_new ("");
  gtk_widget_show (outputjouradh);
  gtk_fixed_put (GTK_FIXED (fixed7), outputjouradh, 144, 240);
  gtk_widget_set_size_request (outputjouradh, 80, 24);

  outputmoisadh = gtk_label_new ("");
  gtk_widget_show (outputmoisadh);
  gtk_fixed_put (GTK_FIXED (fixed7), outputmoisadh, 304, 240);
  gtk_widget_set_size_request (outputmoisadh, 88, 24);

  outputanneeadh = gtk_label_new ("");
  gtk_widget_show (outputanneeadh);
  gtk_fixed_put (GTK_FIXED (fixed7), outputanneeadh, 496, 240);
  gtk_widget_set_size_request (outputanneeadh, 112, 24);

  comboboxentry7 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry7);
  gtk_fixed_put (GTK_FIXED (fixed7), comboboxentry7, 480, 280);
  gtk_widget_set_size_request (comboboxentry7, 101, 24);

  comboboxentry6 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry6);
  gtk_fixed_put (GTK_FIXED (fixed7), comboboxentry6, 280, 288);
  gtk_widget_set_size_request (comboboxentry6, 109, 21);

  comboboxentry5 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry5);
  gtk_fixed_put (GTK_FIXED (fixed7), comboboxentry5, 136, 288);
  gtk_widget_set_size_request (comboboxentry5, 101, 21);

  validermodifadh = gtk_button_new ();
  gtk_widget_show (validermodifadh);
  gtk_fixed_put (GTK_FIXED (fixed7), validermodifadh, 424, 360);
  gtk_widget_set_size_request (validermodifadh, 112, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (validermodifadh), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox8), label37, FALSE, FALSE, 0);

  retrnA2 = gtk_button_new ();
  gtk_widget_show (retrnA2);
  gtk_fixed_put (GTK_FIXED (fixed7), retrnA2, 600, 360);
  gtk_widget_set_size_request (retrnA2, 112, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (retrnA2), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox9), label38, FALSE, FALSE, 0);

  outputprenomadh = gtk_label_new ("");
  gtk_widget_show (outputprenomadh);
  gtk_fixed_put (GTK_FIXED (fixed7), outputprenomadh, 128, 128);
  gtk_widget_set_size_request (outputprenomadh, 128, 24);

  g_signal_connect ((gpointer) validermodifadh, "clicked",
                    G_CALLBACK (on_validermodifadh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifadh, modifadh, "modifadh");
  GLADE_HOOKUP_OBJECT (modifadh, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (modifadh, label22, "label22");
  GLADE_HOOKUP_OBJECT (modifadh, label23, "label23");
  GLADE_HOOKUP_OBJECT (modifadh, label27, "label27");
  GLADE_HOOKUP_OBJECT (modifadh, label29, "label29");
  GLADE_HOOKUP_OBJECT (modifadh, label31, "label31");
  GLADE_HOOKUP_OBJECT (modifadh, label25, "label25");
  GLADE_HOOKUP_OBJECT (modifadh, label24, "label24");
  GLADE_HOOKUP_OBJECT (modifadh, label26, "label26");
  GLADE_HOOKUP_OBJECT (modifadh, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (modifadh, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (modifadh, outputloginadh, "outputloginadh");
  GLADE_HOOKUP_OBJECT (modifadh, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (modifadh, outputmdpssadh, "outputmdpssadh");
  GLADE_HOOKUP_OBJECT (modifadh, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (modifadh, outputnomadh, "outputnomadh");
  GLADE_HOOKUP_OBJECT (modifadh, outputjouradh, "outputjouradh");
  GLADE_HOOKUP_OBJECT (modifadh, outputmoisadh, "outputmoisadh");
  GLADE_HOOKUP_OBJECT (modifadh, outputanneeadh, "outputanneeadh");
  GLADE_HOOKUP_OBJECT (modifadh, comboboxentry7, "comboboxentry7");
  GLADE_HOOKUP_OBJECT (modifadh, comboboxentry6, "comboboxentry6");
  GLADE_HOOKUP_OBJECT (modifadh, comboboxentry5, "comboboxentry5");
  GLADE_HOOKUP_OBJECT (modifadh, validermodifadh, "validermodifadh");
  GLADE_HOOKUP_OBJECT (modifadh, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (modifadh, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (modifadh, image8, "image8");
  GLADE_HOOKUP_OBJECT (modifadh, label37, "label37");
  GLADE_HOOKUP_OBJECT (modifadh, retrnA2, "retrnA2");
  GLADE_HOOKUP_OBJECT (modifadh, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (modifadh, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (modifadh, image9, "image9");
  GLADE_HOOKUP_OBJECT (modifadh, label38, "label38");
  GLADE_HOOKUP_OBJECT (modifadh, outputprenomadh, "outputprenomadh");

  return modifadh;
}

GtkWidget*
create_window8 (void)
{
  GtkWidget *window8;

  window8 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window8), _("window8"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window8, window8, "window8");

  return window8;
}

GtkWidget*
create_supprsucces (void)
{
  GtkWidget *supprsucces;
  GtkWidget *dialog_vbox1;
  GtkWidget *fixed8;
  GtkWidget *label39;
  GtkWidget *dialog_action_area1;
  GtkWidget *oksuppradh;

  supprsucces = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (supprsucces), _("Succ\303\250s"));
  gtk_window_set_type_hint (GTK_WINDOW (supprsucces), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (supprsucces), FALSE);

  dialog_vbox1 = GTK_DIALOG (supprsucces)->vbox;
  gtk_widget_show (dialog_vbox1);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), fixed8, TRUE, TRUE, 0);

  label39 = gtk_label_new (_("Succ\303\250s de supression"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed8), label39, 80, 72);
  gtk_widget_set_size_request (label39, 168, 56);

  dialog_action_area1 = GTK_DIALOG (supprsucces)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  oksuppradh = gtk_button_new_with_mnemonic (_("Ok"));
  gtk_widget_show (oksuppradh);
  gtk_dialog_add_action_widget (GTK_DIALOG (supprsucces), oksuppradh, 0);
  GTK_WIDGET_SET_FLAGS (oksuppradh, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) oksuppradh, "clicked",
                    G_CALLBACK (on_oksuppradh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprsucces, supprsucces, "supprsucces");
  GLADE_HOOKUP_OBJECT_NO_REF (supprsucces, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (supprsucces, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (supprsucces, label39, "label39");
  GLADE_HOOKUP_OBJECT_NO_REF (supprsucces, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (supprsucces, oksuppradh, "oksuppradh");

  return supprsucces;
}

