/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Connection (void);
GtkWidget* create_EspaceAdmin (void);
GtkWidget* create_comptes (void);
GtkWidget* create_adherent (void);
GtkWidget* create_ajoutadh (void);
GtkWidget* create_modifadh (void);
GtkWidget* create_window8 (void);
GtkWidget* create_supprsucces (void);
