/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Essaie1 (void)
{
  GtkWidget *Essaie1;
  GtkWidget *fixed1;
  GtkWidget *mustapha;
  GtkWidget *mhadheb;

  Essaie1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Essaie1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Essaie1), fixed1);

  mustapha = gtk_button_new_with_mnemonic (_("mustapha"));
  gtk_widget_show (mustapha);
  gtk_fixed_put (GTK_FIXED (fixed1), mustapha, 160, 72);
  gtk_widget_set_size_request (mustapha, 104, 32);

  mhadheb = gtk_button_new_with_mnemonic (_("mhadheb"));
  gtk_widget_show (mhadheb);
  gtk_fixed_put (GTK_FIXED (fixed1), mhadheb, 168, 168);
  gtk_widget_set_size_request (mhadheb, 88, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Essaie1, Essaie1, "Essaie1");
  GLADE_HOOKUP_OBJECT (Essaie1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Essaie1, mustapha, "mustapha");
  GLADE_HOOKUP_OBJECT (Essaie1, mhadheb, "mhadheb");

  return Essaie1;
}

